$nav = @'
    <nav class="navbar"><div class="nav-container"><a href="index" class="brand" style="display:flex; align-items:center; text-decoration: none;"><img src="assets/1000105640.png" alt="Logo OSIS IPTO" style="height: 50px; width: auto; border-radius: 8px; object-fit: cover;"></a><ul class="nav-links"><li><a href="index" class="nav-link">Homepage</a></li><li><a href="aboutus" class="nav-link">About Us</a></li><li><a href="anggota" class="nav-link">Anggota</a></li><li class="dropdown"><a href="komunitas" class="nav-link NAV_ACTIVE_K">Komunitas <i class="fa-solid fa-chevron-down" style="font-size: 0.8em; margin-left: 5px;"></i></a><div class="dropdown-content"><a href="komunitas-animation">Animation Community</a><a href="komunitas-revival">Community of Revival</a><a href="komunitas-podcast">Podcast Community</a><a href="komunitas-pmr">PMR Community</a><a href="komunitas-theatre">Theatre Community</a><a href="komunitas-photography">Photography Community</a><a href="komunitas-emagazine">E-Magazine Community</a><a href="komunitas-cooking">Cooking Community</a><a href="komunitas-mural">Mural Community</a><a href="komunitas-dance">Dance Community</a><a href="komunitas-paskibra">Paskibra Community</a><a href="komunitas-music">Music Community</a><a href="komunitas-tech">Tech Community</a></div></li><li class="dropdown"><a href="acara" class="nav-link NAV_ACTIVE_A">Acara <i class="fa-solid fa-chevron-down" style="font-size: 0.8em; margin-left: 5px;"></i></a><div class="dropdown-content"><a href="acara-paskah">Acara Paskah</a><a href="acara-jawa-social-quest">JAWA's Social Quest</a></div></li></ul><a href="contactus" class="btn-contact">Contact Us</a></div></nav>
'@

$style = @'
    <style>
        .club-page{max-width:800px;margin:0 auto;padding:3rem 1.5rem 6rem}.club-page .club-title{text-align:center;font-size:3.5rem;font-weight:800;color:var(--text-main);margin-bottom:1rem;letter-spacing:-1px}.club-page .club-subtitle{text-align:center;font-size:1.15rem;color:var(--text-muted);max-width:600px;margin:0 auto 2.5rem;line-height:1.7;position:relative;padding-top:1.5rem}.club-page .club-subtitle::before{content:'';position:absolute;top:0;left:50%;transform:translateX(-50%);width:60px;height:3px;background:var(--accent-cyan);border-radius:3px}.club-hero-image{width:100%;border-radius:24px;overflow:hidden;margin-bottom:4rem;box-shadow:var(--shadow-xl)}.club-hero-image img{width:100%;height:auto;display:block;aspect-ratio:16/9;object-fit:cover}.club-section{margin-bottom:4rem}.club-section h2{font-size:2rem;font-weight:800;color:var(--text-main);margin-bottom:1.5rem;text-align:center}.club-section p{font-size:1.1rem;color:var(--text-muted);line-height:1.8;text-align:center}.club-section .club-image{width:100%;border-radius:20px;overflow:hidden;margin:2rem 0;box-shadow:var(--shadow-md)}.club-section .club-image img{width:100%;height:auto;display:block;aspect-ratio:16/9;object-fit:cover}.club-cta{background:linear-gradient(135deg,#e57b25 0%,#9b59b6 50%,var(--primary) 100%);border-radius:24px;padding:3.5rem 2.5rem;text-align:center;color:white;margin-top:4rem}.club-cta h3{font-size:1.8rem;font-weight:700;color:white;margin-bottom:1.5rem;line-height:1.4}.club-cta .cta-btn{display:inline-flex;align-items:center;gap:.75rem;background:white;color:var(--primary);padding:.9rem 2rem;border-radius:50px;font-weight:700;font-size:1.05rem;transition:all .3s ease;box-shadow:0 4px 15px rgba(0,0,0,.15)}.club-cta .cta-btn:hover{transform:translateY(-3px);box-shadow:0 8px 25px rgba(0,0,0,.25)}.club-nav{display:flex;justify-content:space-between;gap:1rem;margin-top:4rem}.club-nav a{display:inline-flex;align-items:center;gap:.5rem;background:var(--primary);color:white;padding:.9rem 2rem;border-radius:50px;font-weight:600;transition:all .3s ease}.club-nav a:hover{transform:translateY(-3px);box-shadow:0 8px 20px rgba(44,76,126,.3)}@media(max-width:768px){.club-page .club-title{font-size:2.5rem}.club-page{padding:2rem 1rem 4rem}.club-nav{flex-direction:column}.club-nav a{justify-content:center}}
    </style>
'@

$footer = @'
    <footer><div class="footer-grid"><div class="footer-brand"><h2>OSIS<span>smak</span>IPTO</h2><p>Membentuk pemimpin masa depan yang melayani dengan ketulusan dan berintegritas tinggi berdasarkan iman Kristiani.</p><div class="social-links"><a href="#"><i class="fa-brands fa-instagram"></i></a><a href="#"><i class="fa-brands fa-tiktok"></i></a><a href="#"><i class="fa-brands fa-youtube"></i></a></div></div><div class="footer-links"><h4>Quick Links</h4><ul><li><a href="index">Homepage</a></li><li><a href="aboutus">About Us</a></li><li><a href="anggota">Anggota</a></li><li></li><li><a href="acara">Acara</a></li></ul></div><div class="footer-links"><h4>Contact Us</h4><ul><li><a href="#"><i class="fa-solid fa-location-dot" style="margin-right:10px;"></i> Jl. Macan No.21, Jakarta Barat</a></li><li><a href="#"><i class="fa-solid fa-envelope" style="margin-right:10px;"></i> osis@smakipto.sch.id</a></li><li><a href="#"><i class="fa-brands fa-whatsapp" style="margin-right:10px;"></i> +62 812 3456 7890</a></li></ul></div></div><div class="footer-bottom"><p>&copy; 2026 OSIS SMAK IPEKA Tomang. All rights reserved.</p></div></footer>
'@

function Make-ClubPage($file, $title, $subtitle, $heroImg, $abbr, $whatIs, $practiceImg, $practiceText, $achieveTitle, $achieveImg, $achieveText, $showTitle, $showText, $prevLink, $prevName, $nextLink, $nextName) {
    $navK = $nav.Replace("NAV_ACTIVE_K", "active").Replace("NAV_ACTIVE_A", "")
    $html = @"
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OSIS SMAK IPTO | $title</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
$style
</head>
<body>
$navK

    <main style="padding-top: var(--nav-height);">
        <div class="club-page">
            <h1 class="club-title animate-fade-up">$title</h1>
            <p class="club-subtitle animate-fade-up delay-1">$subtitle</p>

            <div class="club-hero-image animate-fade-up delay-2">
                <img src="$heroImg" alt="$title SMAK IPTO">
            </div>

            <div class="club-section animate-fade-up">
                <h2>WHAT IS $abbr</h2>
                <p>$whatIs</p>
            </div>

            <div class="club-section animate-fade-up">
                <h2>WEEKLY PRACTICE</h2>
                <div class="club-image"><img src="$practiceImg" alt="$title Practice"></div>
                <p>$practiceText</p>
            </div>

            <div class="club-section animate-fade-up">
                <h2>$achieveTitle</h2>
                <div class="club-image"><img src="$achieveImg" alt="$title Achievement"></div>
                <p>$achieveText</p>
            </div>

            <div class="club-section animate-fade-up">
                <h2>$showTitle</h2>
                <p>$showText</p>
            </div>

            <div class="club-cta animate-fade-up">
                <h3>Cari Tahu Informasi Terkini Mengenai SMAK IPTO di Instagram Kami</h3>
                <a href="#" class="cta-btn"><i class="fa-brands fa-instagram" style="font-size: 1.3rem;"></i> @osissmakipto</a>
            </div>

            <div class="club-nav animate-fade-up">
                <a href="$prevLink"><i class="fa-solid fa-arrow-left"></i> $prevName</a>
                <a href="$nextLink">$nextName <i class="fa-solid fa-arrow-right"></i></a>
            </div>
        </div>
    </main>

$footer
</body>
</html>
"@
    $html | Out-File -FilePath $file -Encoding utf8
    Write-Host "Created $file"
}

# Generate all komunitas pages
Make-ClubPage "komunitas-podcast" "Podcast Community" "Podcast Community, Mengeksplorasi Dunia Broadcasting dan Public Speaking melalui Podcast Inspiratif" "https://images.unsplash.com/photo-1589903308904-1010c2294adc?w=1200&q=80" "PC" "Podcast Community (PC) adalah komunitas siswa/i SMAK IPTO yang berfokus pada dunia broadcasting, public speaking, dan produksi konten audio-visual. Komunitas ini menjadi wadah untuk mengasah kemampuan berbicara, membuat konten podcast menarik, dan mempelajari teknik produksi audio profesional." "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=1200&q=80" "Setiap minggu, anggota Podcast Community berlatih teknik public speaking, editing audio, dan merancang konten podcast. Sesi latihan meliputi pelatihan vokal, penulisan naskah, teknik wawancara, dan penggunaan peralatan recording profesional." "KEGIATAN & PRESTASI" "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=1200&q=80" "Podcast Community secara rutin memproduksi episode-episode podcast yang membahas berbagai topik, mulai dari kehidupan sekolah, tips belajar, hingga isu-isu terkini. PC juga berperan sebagai MC dan host di berbagai acara sekolah." "EPISODES" "Dengarkan episode-episode terbaik dari Podcast Community SMAK IPTO! Setiap episode menghadirkan pembahasan menarik dengan narasumber inspiratif dari kalangan guru, alumni, dan tokoh masyarakat." "komunitas-revival" "Revival" "komunitas-pmr" "PMR"

Make-ClubPage "komunitas-pmr" "PMR Community" "PMR Community, Palang Merah Remaja yang Melayani dan Peduli terhadap Kesehatan Warga Sekolah" "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=1200&q=80" "PMR" "PMR Community adalah komunitas Palang Merah Remaja SMAK IPTO yang berfokus pada pelayanan kesehatan, pertolongan pertama, dan kepedulian sosial. Anggota PMR dilatih untuk siap siaga menghadapi situasi darurat dan memberikan pertolongan pertama kepada warga sekolah." "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1200&q=80" "Setiap minggu, anggota PMR berlatih teknik pertolongan pertama (P3K), CPR, dan penanganan keadaan darurat. Sesi latihan juga mencakup edukasi kesehatan, donor darah, dan simulasi penanganan bencana." "KEGIATAN & PELAYANAN" "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=1200&q=80" "PMR aktif dalam menjaga kesehatan warga sekolah melalui pos kesehatan, kampanye hidup sehat, dan kerja sama dengan Palang Merah Indonesia. Anggota PMR juga berpartisipasi dalam lomba PMR tingkat kota dan provinsi." "DAMPAK" "PMR Community telah menjadi garda terdepan dalam menjaga kesehatan dan keselamatan warga SMAK IPTO. Kehadiran anggota PMR di setiap kegiatan sekolah memberikan rasa aman dan nyaman bagi seluruh siswa dan guru." "komunitas-podcast" "Podcast" "komunitas-theatre" "Theatre"

Make-ClubPage "komunitas-theatre" "Theatre Community" "Theatre Community, Ekspresi Diri melalui Seni Peran, Drama, dan Panggung Teater" "https://images.unsplash.com/photo-1507676184212-d0330a15673c?w=1200&q=80" "TC" "Theatre Community adalah komunitas seni peran SMAK IPTO yang mengeksplorasi dunia teater, drama, dan panggung. Anggota belajar akting, improvisasi, penulisan naskah drama, serta tata panggung untuk menghasilkan pertunjukan yang memukau." "https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80" "Setiap minggu, anggota Theatre Community berlatih teknik akting, olah vokal, dan olah tubuh. Sesi latihan juga mencakup latihan improvisasi, membaca naskah, dan blocking untuk persiapan pertunjukan." "KEGIATAN & PERTUNJUKAN" "https://images.unsplash.com/photo-1547153760-18fc86324498?w=1200&q=80" "Theatre Community tampil di berbagai acara sekolah dengan pertunjukan drama, musikal, dan sketsa. Komunitas ini juga aktif mengikuti festival teater pelajar dan menggelar pertunjukan tahunan yang selalu dinantikan warga sekolah." "PANGGUNG" "Setiap pertunjukan Theatre Community menghadirkan cerita yang penuh makna dan emosi. Dari drama klasik hingga karya orisinal, setiap panggung menjadi ajang bagi anggota TC untuk menunjukkan bakat seni peran terbaik mereka." "komunitas-pmr" "PMR" "komunitas-photography" "Photography"

Make-ClubPage "komunitas-photography" "Photography Community" "Photography Community, Menangkap Momen Terbaik dan Mempelajari Teknik Fotografi Profesional" "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1200&q=80" "PC" "Photography Community adalah komunitas siswa/i SMAK IPTO yang memiliki passion di bidang fotografi. Anggota belajar teknik fotografi mulai dari komposisi, pencahayaan, editing, hingga storytelling visual untuk menghasilkan foto-foto berkualitas profesional." "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=1200&q=80" "Setiap minggu, anggota Photography Community berlatih berbagai teknik fotografi seperti portrait, landscape, street photography, dan product photography. Sesi juga mencakup tutorial editing menggunakan Lightroom dan Photoshop." "KEGIATAN & PRESTASI" "https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=1200&q=80" "Photography Community menjadi dokumentator resmi setiap acara sekolah, dari upacara hingga event besar. Anggota juga aktif mengikuti kompetisi fotografi pelajar dan pameran foto bersama." "GALERI" "Hasil karya Photography Community dipamerkan secara berkala melalui pameran foto sekolah dan media sosial. Setiap foto menceritakan kisah dan momen berharga kehidupan siswa/i SMAK IPTO." "komunitas-theatre" "Theatre" "komunitas-emagazine" "E-Magazine"

Make-ClubPage "komunitas-emagazine" "E-Magazine Community" "E-Magazine Community, Mewujudkan Jurnalisme Sekolah melalui Artikel, Liputan, dan Majalah Digital" "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&q=80" "EMC" "E-Magazine Community (EMC) adalah komunitas jurnalistik dan penerbitan digital SMAK IPTO. Anggota belajar menulis artikel, melakukan liputan, desain layout majalah, dan memproduksi konten digital berkualitas untuk majalah sekolah." "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1200&q=80" "Setiap minggu, anggota EMC berlatih penulisan jurnalistik, teknik wawancara, desain grafis, dan editing konten. Sesi juga mencakup rapat editorial untuk merencanakan edisi majalah berikutnya." "KEGIATAN & PUBLIKASI" "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=1200&q=80" "EMC secara rutin menerbitkan majalah digital yang berisi berita sekolah, feature story, opini siswa, dan konten kreatif lainnya. Majalah digital EMC menjadi sumber informasi utama bagi seluruh warga sekolah." "EDISI" "Setiap edisi E-Magazine menghadirkan tema yang berbeda dan menarik, dari profil guru dan alumni inspiratif, liputan kegiatan sekolah, hingga tips dan trik bermanfaat untuk siswa/i SMAK IPTO." "komunitas-photography" "Photography" "komunitas-cooking" "Cooking"

Make-ClubPage "komunitas-cooking" "Cooking Community" "Cooking Community, Berkreasi dengan Rasa dan Mengembangkan Keahlian Tata Boga" "https://images.unsplash.com/photo-1556910103-1c02745a872f?w=1200&q=80" "CC" "Cooking Community (CC) adalah komunitas kuliner SMAK IPTO yang menjadi wadah bagi siswa/i pecinta masak-memasak. Anggota belajar berbagai teknik memasak, food presentation, dan mengeksplorasi resep-resep dari berbagai budaya." "https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?w=1200&q=80" "Setiap minggu, anggota Cooking Community berlatih memasak berbagai jenis hidangan, mulai dari appetizer, main course, hingga dessert. Sesi latihan juga mencakup teknik food styling dan food photography." "KEGIATAN & PRESTASI" "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1200&q=80" "Cooking Community sering mengadakan cooking demo, food bazaar di acara sekolah, dan workshop memasak untuk siswa lainnya. CC juga aktif mengikuti kompetisi memasak antar pelajar." "MENU SPESIAL" "Setiap semester, Cooking Community mempersembahkan menu spesial yang terinspirasi dari berbagai masakan nusantara dan internasional. Kreativitas dan cita rasa menjadi kunci utama dalam setiap hidangan yang dihasilkan." "komunitas-emagazine" "E-Magazine" "komunitas-mural" "Mural"

Make-ClubPage "komunitas-mural" "Mural Community" "Mural Community, Menghidupkan Tembok Sekolah dengan Karya Seni Lukis dan Warna Warni Mural" "https://images.unsplash.com/photo-1499806489304-20a2cc47b2c5?w=1200&q=80" "MC" "Mural Community (MC) adalah komunitas seni rupa SMAK IPTO yang berfokus pada seni mural dan lukis dinding. Anggota belajar teknik menggambar, komposisi warna, dan mengubah dinding-dinding sekolah menjadi kanvas seni yang indah dan bermakna." "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=1200&q=80" "Setiap minggu, anggota Mural Community berlatih sketsa, teknik cat, dan perencanaan desain mural. Sesi juga mencakup studi warna, tipografi, dan eksplorasi gaya seni dari berbagai aliran." "KEGIATAN & KARYA" "https://images.unsplash.com/photo-1561059488-916d69792237?w=1200&q=80" "Mural Community bertanggung jawab mempercantik lingkungan sekolah melalui karya mural yang inspiratif. Setiap mural mengandung pesan positif dan mencerminkan identitas SMAK IPTO." "GALERI MURAL" "Karya-karya Mural Community tersebar di berbagai sudut sekolah, dari koridor, kantin, hingga aula. Setiap mural menjadi ikon visual yang memperkaya estetika lingkungan belajar siswa/i SMAK IPTO." "komunitas-cooking" "Cooking" "komunitas-dance" "Dance"

Make-ClubPage "komunitas-dance" "Dance Community" "Dance Community, Komunitas Tari Modern dan Tradisional untuk Mengekspresikan Talenta Gerak" "https://images.unsplash.com/photo-1508700929628-666bc8bd84ea?w=1200&q=80" "DC" "Dance Community (DC) adalah komunitas tari SMAK IPTO yang mengeksplorasi berbagai genre tarian, dari modern dance, K-pop, hip-hop, hingga tari tradisional Indonesia. Anggota belajar koreografi, ekspresi gerak, dan tampil di berbagai panggung." "https://images.unsplash.com/photo-1535525153412-30a0c3beb4c0?w=1200&q=80" "Setiap minggu, anggota Dance Community berlatih koreografi baru, latihan fisik, dan teknik dasar tari. Sesi juga mencakup latihan formasi, sinkronisasi, dan persiapan untuk penampilan di berbagai acara." "KEGIATAN & PENAMPILAN" "https://images.unsplash.com/photo-1547153760-18fc86324498?w=1200&q=80" "Dance Community tampil memukau di setiap acara sekolah, dari opening ceremony, perayaan hari besar, hingga event tahunan. DC juga aktif mengikuti kompetisi dance antar sekolah." "PANGGUNG" "Setiap penampilan Dance Community selalu dinantikan oleh seluruh warga sekolah. Energi, kreativitas, dan semangat para penari DC berhasil menghidupkan suasana di setiap panggung yang mereka pijak." "komunitas-mural" "Mural" "komunitas-paskibra" "Paskibra"

Make-ClubPage "komunitas-paskibra" "Paskibra Community" "Paskibra Community, Menjunjung Tinggi Kedisiplinan dan Rasa Nasionalisme melalui Baris Berbaris" "https://images.unsplash.com/photo-1541512416146-368bb1590fb4?w=1200&q=80" "PBC" "Paskibra Community adalah komunitas Pasukan Pengibar Bendera SMAK IPTO yang menanamkan kedisiplinan, kepemimpinan, dan rasa nasionalisme. Anggota dilatih dalam baris-berbaris, tata upacara, dan pengibaran bendera dengan penuh khidmat." "https://images.unsplash.com/photo-1529390079861-591de354faf5?w=1200&q=80" "Setiap minggu, anggota Paskibra berlatih baris-berbaris, formasi, dan tata upacara bendera. Latihan rutin ini membentuk kedisiplinan, ketangguhan fisik, dan mental para anggota." "KEGIATAN & PRESTASI" "https://images.unsplash.com/photo-1544027993-37dbfe43562a?w=1200&q=80" "Paskibra tampil di setiap upacara bendera sekolah, peringatan hari kemerdekaan, dan acara-acara resmi lainnya. Komunitas ini juga aktif mengikuti lomba PBB dan berperan penting dalam menanamkan semangat nasionalisme." "DEDIKASI" "Paskibra Community adalah simbol kedisiplinan dan kebanggaan SMAK IPTO. Setiap langkah dan gerakan para anggotanya mencerminkan jiwa nasionalisme dan tanggung jawab sebagai generasi penerus bangsa." "komunitas-dance" "Dance" "komunitas-music" "Music"

Make-ClubPage "komunitas-music" "Music Community" "Music Community, Berkarya dan Bermain Musik Bersama dari Alat Musik Klasik hingga Modern" "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&q=80" "MC" "Music Community adalah komunitas musik SMAK IPTO yang menjadi wadah bagi para pecinta musik. Anggota belajar bermain berbagai alat musik, berlatih vokal, aransemen lagu, dan tampil di berbagai panggung musik sekolah." "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=1200&q=80" "Setiap minggu, anggota Music Community berlatih bermain alat musik (gitar, piano, drum, bass), vokal, dan aransemen lagu. Sesi juga mencakup latihan band, jamming session, dan persiapan untuk penampilan." "KEGIATAN & PENAMPILAN" "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=80" "Music Community tampil di berbagai acara sekolah sebagai band pengiring, performer solo, maupun ensemble. Komunitas ini juga mengadakan konser tahunan dan mengikuti festival musik pelajar." "REPERTOIRE" "Dari lagu pop, rock, jazz, hingga musik rohani, Music Community menguasai beragam genre musik. Setiap penampilan menunjukkan keahlian dan passion para anggota dalam bermusik." "komunitas-paskibra" "Paskibra" "komunitas-tech" "Tech"

Write-Host "All komunitas pages generated!"
